spring:
  datasource:
    url: jdbc:mysql://localhost:3306/z?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true #打印sql
    properties:
      hibernate:
        format_sql: true #格式化sql
server:
  port: 8082
mybatis:
  configuration:
    map-underscore-to-camel-case: true
# 禁用缓存
spring.thymeleaf.cache: false

login.urls: http://localhost:8081/#/login